export const SliderData = [
    {
      image:
        'https://baner-kursak.s3.eu-west-2.amazonaws.com/baner1.webp'
    },
    {
      image:
        'https://baner-kursak.s3.eu-west-2.amazonaws.com/baner2.webp'
    },
    {
      image:
        'https://baner-kursak.s3.eu-west-2.amazonaws.com/baner3.webp'
    },
    {
      image:
        'https://baner-kursak.s3.eu-west-2.amazonaws.com/baner4.webp'
    },
    {
      image:
        'https://baner-kursak.s3.eu-west-2.amazonaws.com/baner5.webp'
    }
  ];