export const SliderData = [
    {
      image:
        'https://alexstsorageblops.blob.core.windows.net/magic/baner1.webp'
    },
    {
      image:
        'https://alexstsorageblops.blob.core.windows.net/magic/baner2.webp'
    },
    {
      image:
        'https://alexstsorageblops.blob.core.windows.net/magic/baner3.webp'
    },
    {
      image:
        'https://alexstsorageblops.blob.core.windows.net/magic/baner4.webp'
    },
    {
      image:
        'https://alexstsorageblops.blob.core.windows.net/magic/baner5.webp'
    }
  ];